describe('Task 1- Create new user and login with same user', () => {
    it('Validate new user and login with same user- Using css Locator', () => {
        cy.visit('https://ineuron-courses.vercel.app/')
        cy.contains('Log in').click()
        cy.contains('New user? Signup').click()
        cy.contains('Sign up').should('not.be.enabled')
        cy.get('input#name').type('RaghavGoli')
        cy.get('input#email').type('venkata.rg@gmail.com')
        cy.get('input#password').type('ineuron')
        cy.get('div.interests-div>div:nth-child(9)>input').click({force:true})
        cy.get('body > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > form:nth-child(1) > div:nth-child(1) > div:nth-child(8) > div:nth-child(1) > input:nth-child(1)').click({force:true})
        cy.get('select#state').select('Goa').should('have.value', 'Goa')
        cy.contains('Sign up').click()
        cy.get('input#email1').type('venkata.rg@gmail.com')
        cy.get('input#password1').type('ineuron')
        cy.contains('Sign in').click({force:true})
        cy.get('h4.welcomeMessage').should("be.visible")
        cy.contains('Sign out').click()
        cy.contains('Sign in').should('be.enabled')
    })
})


describe('Task 2- Create new user and login with same user', () => {
    it.only('Validate new user and login with same user- Using XPATH Locator', () => {
        cy.visit('https://ineuron-courses.vercel.app/')
        cy.contains('Log in').click()
        cy.contains('New user? Signup').click()
        cy.contains('Sign up').should('not.be.enabled')
        cy.xpath("//input[@id='name']").type('RaghavGoli1')
        cy.xpath("//input[@id='email']").type('venkata.rg123@gmail.com')
        cy.xpath("//input[@id='password']").type('ineuron')
        cy.xpath("//label[normalize-space()='Testing']/preceding-sibling::input").click({force:true})
        cy.xpath("//div[@class='genders-div']//div[2]//input[1]").click({force:true})
        cy.xpath("//select[@id='state']").select('Goa').should('have.value', 'Goa')
        cy.contains('Sign up').click()
        cy.xpath("//input[@id='email1']").type('venkata.rg123@gmail.com')
        cy.xpath("//input[@id='password1']").type('ineuron')
        cy.contains('Sign in').click({force:true})
        cy.xpath("//h4[@class='welcomeMessage']").should("be.visible")
        cy.contains('Sign out').click()
        cy.contains('Sign in').should('be.enabled')
    })
})